version: '3'

services:
  restful:
    container_name: "restful_api"
    restart: always
    build: .
    #command: gunicorn --workers=3 --worker-class=eventlet restful.wsgi:application --bind 0.0.0.0:8000 --error-logfile ./logs/restful.log --capture-output
    command: gunicorn restful.wsgi:application --error-logfile ./logs/restful.log --capture-output
    volumes:
      - ~/docker-volumes/logs/:/usr/src/app/logs/
    ports:
      - 8000:8000
    environment:
      - DEBUG=True
      - SECRET_KEY=-c9c=j+az@0-k*hdz_st3^hain4*t0_b-^pmzbis!i1cjb$$+#*
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=restful
      - DJANGO_SETTINGS_MODULE=restful.settings
      - DB_USER=postgres
      - DB_PASSWORD=postgres